version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'DEM'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
    command: jupyter-lab